### ISSUE TITLE
paystack doesn't pick the coverted currency figure if open cart support multicurrency currency

### ISSUE THREAD

**Issue by williams9438** [PaystackHQ/plugin-opencart-3.x#4]

**Comment by williams9438** [comment]
i have resolved the issue by setting naira as the default currency and others then follow since opencart picks up the default currency (which in this case is naira) and other payment gateway can be used for other currencies

**Comment by steveamaza** [comment]
@williams9438 this has now been resolved. Allowed currencies on Paystack are NGN, GHS, and USD
